export default {
	AGREED_TO_RENTAL_TERMS: 'AGREED_TO_RENTAL_TERMS',
	SET_SPORTING_GOOD: 'SET_SPORTING_GOOD',
	ADD_RENTAL: 'ADD_RENTAL',
	DETACH_SPORTING_GOOD: 'DETACH_SPORTING_GOOD',
	DETACH_SPORTING_GOOD_RENTAL: 'DETACH_SPORTING_GOOD_RENTAL',
	ATTACH_SPORTING_GOOD_RENTAL: 'ATTACH_SPORTING_GOOD_RENTAL'
}
