export default {
	FETCH_CURRENT_USER: 'FETCH_CURRENT_USER',
	SET_CURRENT_USER: 'SET_CURRENT_USER',
	SET_CURRENT_USER_RENTALS: 'SET_CURRENT_USER_RENTALS',
	CLEAR_SESSION: 'CLEAR_SESSION',
	DROP_SESSION_DATA: 'DROP_SESSION_DATA'
}
